name: Build SDK References Documents

on:
  release:
    types: [published]
    branches: [ main ]
    secrets:
      OSS_USERNAME:
        required: true
      OSS_PASSWORD:
        required: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Restore gradle.properties
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
        OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
      run: |
        echo "ossusername=${OSS_USERNAME}" > ./gradle.properties
        echo "osspassword=${OSS_PASSWORD}" >> ./gradle.properties
    - name: Build
      run: |
        sh ./gradlew dokkaHtml
    - name: Commit and push docs
      working-directory: ./
      run: |
        git config --global user.email "wiley@nurigo.net"
        git config --global user.name "Github Actions"
        git add ./docs
        git commit -m "Update SDK API References"
        git push -u origin main
